import React from 'react';
import '../styles/experiment_new.css';

class NewExperimentPage extends React.Component {
	constructor(props) {
		super(props);
	}

	render() {
		return (
			<div class="main">
				<h2>New Experiment</h2>
				<form class="newExperimentForm" action="" method="post">
					<div class="formGroup">
						<label>Experiment ID <em>(autogenerated)</em></label><span class="experimentId">01</span>
					</div>
					<div class="formGroup">
						<label>Experiment Name</label>
						<input type="text" name="name" tabindex="1" />
					</div>
					<div class="formGroup">
						<label>Experiment Description</label>
						<input type="text" name="description" tabindex="2" />
					</div>
				</form>
			</div>
		);
	}
}

export default NewExperimentPage;