import React from 'react';
import '../styles/experiment_new.css';

class NewExperimentPage extends React.Component {
	render() {
		return (
			<div className="newExperimentArea">
				<h2>New Experiment</h2>
				<form className="newExperimentForm" action="" method="post">
					<div className="formGroup">
						<label>Experiment ID </label><span className="experimentId"><em>(autogenerated)</em></span>
					</div>
					<div className="formGroup">
						<label>Experiment Name</label>
						<input type="text" name="experimentName" tabIndex="1" />
					</div>
					<div className="formGroup">
						<label>Experiment Description</label>
						<input type="text" name="experimentDescription" tabIndex="2" />
					</div>
				</form>
			</div>
		);
	}
}

export default NewExperimentPage;